ejercicios Dino
Amerike-dev/InteligenciaArtificial pull request #27
Opened 2022-10-01 23:11 UTC by Dinorekkos

2022-10-02 17:28 UTC, BanyoAmerike requested changes

2022-10-02 17:28 UTC, BanyoAmerike commented on Ejercicios/Tercer Ejercicio/Fernando Cossio/GridGenerator.cs
> +        if (_withOffset) GenerateGrid(_xSize, _ySize, _xOffset, _yOffset); else GenerateGrid(_xSize, _ySize);
Para evitar que tengas un if else llamando a la misma funcion, utiliza argumentos opcionales.

```
GenerateGrid(_xSize,_ySize, xOffset, _yOffseet)
```
Y en tu funcion declaras cuales son necesarios y cuales opcionales
```
public void GenerateGrid(int width, int height, float xGap = 0, float yGap = 0)
```
El 0 en `xGap` y en `yGap` hace que si no se ponen cuando se llama la funcion tomen ese valor como por default.

Cambialo.
-0.5 puntos

2022-10-02 17:28 UTC, BanyoAmerike commented on Tareas/Cuarta Tarea/Fernando Cossio/Recursion.cs
> +        return 1 + CountArray(array[1..]);
Esta linea esta mal, revisala.
-0.5 puntos

2022-10-02 17:29 UTC, BanyoAmerike requested changes

2022-10-02 17:29 UTC, BanyoAmerike commented on Tareas/Cuarta Tarea/Diana Ramos Garcia/Recursividad.cs
> +
Elimina este espacio innecesario
-0.1 puntos por espacios innecesarios que vea en el codigo

2022-10-03 21:57 UTC, BanyoAmerike approved these changes

2022-10-03 21:57 UTC, BanyoAmerike approved these changes

2022-10-03 22:26 UTC, Fernando747400 commented on Tareas/Cuarta Tarea/Fernando Cossio/Recursion.cs
> +        return 1 + CountArray(array[1..]);
En C# si funciona

2022-10-07 17:20 UTC, BanyoAmerike approved these changes

2022-10-07 17:20 UTC, merged